server:
  port: 7050
  servlet:
    context-path: /springcloud-sample-provider-inventory
eureka:
  instance:
    hostname: 192.168.1.208
  client:
    serviceUrl:
      defaultZone: http://192.168.1.208:7000/eureka/
