server:
  port: 7000

eureka:
  instance:
    hostname: 192.168.1.208
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.1.208:7000/eureka/
